language: ruby
rvm:
  - 1.9.3
  - 2.3.1
  - jruby
env:
  - PROTOBUF_VERSION=2.6.1
  - PROTOBUF_VERSION=3.0.0-alpha-2
matrix:
  allow_failures:
    - env: PROTOBUF_VERSION=3.0.0-alpha-2
before_install:
  - gem install bundler -v 1.12.5
script: NO_COMPILE_TEST_PROTOS=1 bundle _1.12.5_ exec rake spec/lib
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/51a956bcd2b1854d6756
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: rubygems
  api_key:
    secure: iQ9JnUKw2CaOGUSR2dSYQ6z3Kp55GkZ0s5ZYq5EQ2KW94hJh1Mn7t3hUnga7IW569lGQyjnWziLRW0GAVxu3q+RrT2OwZJYB/di39kv1IJTQpXbFI7bm/AvbYba2t3mFgMLpPGEmxemyAQ1AigbEu/5V5DssfF6Qkh6jiMuphaY=
  gem: protobuffy
  on:
    repo: lookout/protobuffy
