before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq3-dev
  - sudo -E ./install-protobuf.sh
  - java -Xmx1g -version
  - javac -J-Xmx1g -version
  - export JRUBY_OPTS=-J-Xmx1g
  # Required for rainbow installation issue, https://github.com/sickill/rainbow/issues/44
  - gem update --system
  - gem update bundler
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.2.2
  - 2.3
  - jruby-9.1.7.0
  - rbx-2
env:
  - PROTOBUF_VERSION=2.6.1
  - PROTOBUF_VERSION=3.0.0-alpha-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - env: PROTOBUF_VERSION=3.0.0-alpha-2
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/51a956bcd2b1854d6756
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: rubygems
  api_key:
    secure: iQ9JnUKw2CaOGUSR2dSYQ6z3Kp55GkZ0s5ZYq5EQ2KW94hJh1Mn7t3hUnga7IW569lGQyjnWziLRW0GAVxu3q+RrT2OwZJYB/di39kv1IJTQpXbFI7bm/AvbYba2t3mFgMLpPGEmxemyAQ1AigbEu/5V5DssfF6Qkh6jiMuphaY=
  gem: protobuffy
  on:
    repo: lookout/protobuffy
